name: Android / Install APK

on:
  push:
    branches: [ "tryactions" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install ADB
      run: |
        sudo apt-get install android-tools-adb

    - name: Run ADB commands
      run: |
        adb devices
        ls -l 
        adb install ./example.apk
        # Add more ADB commands as needed

