name: Telemetry Automation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  tests:
    runs-on: self-hosted

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
      
        - name: Set up Docker
          uses: docker/setup-buildx-action@v3
      
        - name: Build Docker image
          run: |
              docker build -t my-robot-tests:latest .
            
        - name: Build and run Robot Framework Docker container
          run: |
                docker run dockerImage
    

