name: Telemetry Automation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  tests:
    runs-on: self-hosted

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
      
        - name: Update Docker Buildx
          run: |
            docker buildx version --builder default
            docker buildx version --builder my-builder-name  # If you have a specific builder

        - name: Set up Docker
          uses: docker/setup-buildx-action@v2
          
        - name: Set up Docker
          uses: docker/build-push-action@v2
