name: Telemetry Automation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  tests:
    runs-on: self-hosted

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Docker Image
          uses: docker/setup-buildx-action@v3
          
        -  name: Build and push
           uses: docker/build-push-action@v5
           with:
              context: .
              file: ./Dockerfile
              push: true
        - name: Run a shell command
          run: |
              echo "Hello from the self-hosted runner!"
          # Add more commands as needed
      
    
