name: user space

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out my other private repo
      uses: actions/checkout@main
      with:
          repository: sheetalgcin/pythonTest
    
    - name: get the path
      run: 
        ls      
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Choose your desired Python version
        
    - name: get the path
      run: 
        ls
        python3 ./github/workflows/parseyaml.py
  
